### ISSUE TITLE
关于docker-maven-plugin构建镜像时出错

### ISSUE THREAD

**Issue by honghongwen** [macrozheng/mall-learning#62]
你好，问下为啥我用docker-maven-plugin 构建镜像时报错呢，是有什么schema需要指定么 0 0 

[INFO] Building image mall/mall-admin:1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.478 s
[INFO] Finished at: 2020-07-24T11:26:03+08:00
[INFO] Final Memory: 70M/819M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.1.0:build (build-image) on project mall-admin: Exception caught: Schema specific part is opaque. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:1.1.0:build (build-image) on project mall-admin: Exception caught
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:151)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:324)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.IllegalArgumentException: Schema specific part is opaque.
        at com.spotify.docker.client.shaded.org.glassfish.jersey.uri.internal.JerseyUriBuilder.checkSsp(JerseyUriBuilder.java:714)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:356)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:153)
        at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:59)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1412)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1402)
        at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:623)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:403)
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:149)
        ... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by macrozheng** [comment]
应该是Docker版本和`docker-maven-plugin`插件版本不兼容问题，将插件升级到`1.2.2`版本可以解决。

**Comment by ForsythiaSuspensa** [comment]
same question

**Comment by kangchengkun** [comment]
In macos, you need to enable the enable the remote Docker API by run `docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 2376:2375 bobrik/socat TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock`
